import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { orbitron } from "@/fonts/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "nhserver web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${orbitron.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
